### PR TITLE
add chef exception handler

### PR DESCRIPTION
**Pull request by cwjohnston**

### CODE REVIEW

**Comment by ampledata** [comment]
OMG YES.

**Comment by cwjohnston** [comment]
@ampledata any chance you have tested this branch? I haven't put it into use in our org but I'm inclined just to ship it anyway.

**Comment by jarosser06** [comment]
@cwjohnston we have started testing it in our staging environment and it seems to be working pretty well.  Looking forward to the new release.

**Comment by jarosser06** [comment]
Would you consider changing the message color to red?

**Comment by damacus** [comment]
This'll be pretty handy for us (and I'm guessing everyone else using chef/hipchat). 

It'll be a straight swap out for the campfire plugin we're using now.

**Comment by cwjohnston** [comment]
@jarosser06 I just pushed changes that allow the color to be configured, and it now defaults to red.

**Comment by josegonzalez** [comment]
Is this mergeable yet?

**Pull request merged**
